version: "3"
services:
  airflow:
    image: apache/airflow
    container_name: airflow
    # restart: unless-stopped
    ports:
     - "8080:8080"
     - "8888:8888"
    environment:
     - AIRFLOW__SCHEDULER__STATSD_ON=True
     - AIRFLOW__SCHEDULER__STATSD_HOST=datadog
     - AIRFLOW__SCHEDULER__STATSD_PORT=8125
     - AIRFLOW__SCHEDULER__STATSD_PREFIX=airflow
    networks:
     - main
  # agent section
  datadog:
    image: datadog/agent:latest
    container_name: datadog
    ports:
     - "8125:8125/udp"
    links:
     - airflow
    environment:
     - DD_API_KEY=e9177a684cfebc3a0be5583d03644da8
     - DD_HOSTNAME=AIRFLOW-PROD
     - DD_APM_ENABLED=true
     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
     - DD_DOGSTATSD_ORIGIN_DETECTION=true
     - DD_AC_INCLUDE="image:*"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    networks:
     - main
networks:
   main:
