apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-flower
  labels:
    app: {{ template "airflow.name" . }}-flower
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "airflow.name" . }}-flower
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}-flower
          image: {{ .Values.airflow.image }}:{{ .Values.airflow.imageTag }}
          imagePullPolicy: {{ .Values.airflow.image_pull_policy }}

          env:
            {{- range $setting, $option := .Values.airflow.config }}
            - name: {{ $setting }}
              value: {{ $option }}
            {{- end }}
          ports:
            - name: flower
              containerPort: {{ .Values.celery.port }}
              protocol: TCP
          args: ["flower"]
          livenessProbe:
            failureThreshold: 20
            httpGet:
              path: /
              port: {{ .Values.celery.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            failureThreshold: 20
            httpGet:
              port: {{ .Values.celery.port }}
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
  selector:
    matchLabels:
      app: {{ template "airflow.name" . }}-flower
