apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-web
  labels:
    app: {{ template "airflow.name" . }}-web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app:  {{ template "airflow.name" . }}-web
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}-web
          image: {{ .Values.images.airflow.repository }}:{{ .Values.images.airflow.tag }}
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy}}
          ports:
            - name: web
              containerPort: {{ .Values.ports.airflowUI }}
              protocol: TCP
          env:
            {{- range $setting, $option := .Values.env }}
            - name: {{ $setting }}
              value: {{ $option }}
            {{- end }}
          args: ["webserver"]
          livenessProbe:
            httpGet:
              path: /health
              port: web
            initialDelaySeconds: {{ .Values.webserver.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webserver.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.webserver.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.webserver.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              port: {{ .Values.ports.airflowUI }}
              path: /health
            initialDelaySeconds: {{ .Values.webserver.readinessProbe.initialDelaySeconds | default 15 }}
            periodSeconds: {{ .Values.webserver.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.webserver.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.webserver.readinessProbe.failureThreshold }}

  selector:
    matchLabels:
      app: {{ template "airflow.name" . }}-web
