apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-worker
  labels:
    app: {{ template "airflow.name" . }}-worker
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{.Values.workers.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app:  {{ template "airflow.name" . }}-worker
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: {{ .Values.secrets.name }}
      containers:
        - name: {{ .Chart.Name }}-web
          image: {{ .Values.images.airflow.repository }}:{{ .Values.images.airflow.tag }}
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy}}
          ports:
            - name: worker
              containerPort: {{ .Values.ports.workerLogs }}
              protocol: TCP
          env:
            {{- range $setting, $option := .Values.env }}
            - name: {{ $setting }}
              value: {{ $option }}
            {{- end }}
          args: ["worker"]
          resources:
            limits:
              cpu: {{ .Values.workers.resources.limits.cpu }}
              memory: {{ .Values.workers.resources.limits.memory }}
            requests:
              cpu: {{ .Values.workers.resources.requests.cpu }}
              memory: {{ .Values.workers.resources.requests.memory }}

  selector:
    matchLabels:
      app: {{ template "airflow.name" . }}-worker
