apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-flower
  labels:
    app: {{ template "airflow.name" . }}-flower
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.flower.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "airflow.name" . }}-flower
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}-flower
          image: {{ .Values.images.airflow.repository }}:{{ .Values.images.airflow.tag }}
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
          env:
            {{- range $key, $option := .Values.flower.env }}
            - name: {{ $key }}
              value: {{ $option }}
            {{- end }}
          ports:
            - name: flower
              containerPort: {{ .Values.ports.flowerUI }}
              protocol: TCP
          args: ["flower"]
          livenessProbe:
            failureThreshold: {{ .Values.flower.livenessProbe.failureThreshold }}
            httpGet:
              path: /
              port: {{ .Values.ports.flowerUI }}
            initialDelaySeconds: {{ .Values.flower.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.flower.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.flower.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.flower.readinessProbe.failureThreshold }}
            httpGet:
              port: {{ .Values.ports.flowerUI }}
              path: /
            initialDelaySeconds: {{ .Values.flower.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.flower.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.flower.readinessProbe.timeoutSeconds }}
  selector:
    matchLabels:
      app: {{ template "airflow.name" . }}-flower
