apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-rabbitmq
  labels:
    app: {{ template "airflow.name" . }}-rabbitmq
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "airflow.name" . }}-rabbitmq
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}-rabbitmq
          image: {{ .Values.images.rabbitmq.repository }}:{{ .Values.images.rabbitmq.tag}}
          imagePullPolicy: {{ .Values.images.rabbitmq.pullPolicy }}
          env:
            {{- range $key, $option := .Values.rabbitmq.env }}
            - name: {{ $key }}
              value: {{ $option }}
            {{- end }}
          ports:
            - name: node
              containerPort: {{ .Values.ports.rabbitmqNode }}
            - name: management
              containerPort: {{ .Values.ports.rabbitmqManagement }}
  selector:
    matchLabels:
      app: {{ template "airflow.name" . }}-rabbitmq
