apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-web
  labels:
    app: {{ template "airflow.name" . }}-web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.airflow.service.type }}
  selector:
    app: {{ template "airflow.name" . }}-web
    release: {{ .Release.Name }}
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.airflow.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-flower
  labels:
    app: {{ template "airflow.name" . }}-flower
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.celery.service.type }}
  selector:
    app: {{ template "airflow.name" . }}-flower
    release: {{ .Release.Name }}
  ports:
    - name: flower
      protocol: TCP
      port: {{ .Values.celery.port }}
---
# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-worker
  labels:
    app: {{ template "airflow.name" . }}-worker
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: worker
      protocol: TCP
      port: 8793
  clusterIP: None
  selector:
    app: {{ template "airflow.name" . }}-worker

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-rabbitmq
  labels:
    app: {{ template "airflow.name" . }}-rabbitmq
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: node
      protocol: TCP
      port: 5672
      targetPort: node
    - name: management
      protocol: TCP
      port: 15672
      targetPort: management