apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-web
  labels:
    app: {{ template "airflow.name" . }}-web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.webserver.service.type }}
  selector:
    app: {{ template "airflow.name" . }}-web
    release: {{ .Release.Name }}
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.ports.airflowUI }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-flower
  labels:
    app: {{ template "airflow.name" . }}-flower
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.flower.service.type }}
  selector:
    app: {{ template "airflow.name" . }}-flower
    release: {{ .Release.Name }}
  ports:
    - name: flower
      protocol: TCP
      port: {{ .Values.ports.flowerUI }}
---
# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-worker
  labels:
    app: {{ template "airflow.name" . }}-worker
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: worker
      protocol: TCP
      port: {{ .Values.ports.workerLogs }}
  clusterIP: None
  selector:
    app: {{ template "airflow.name" . }}-worker

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: {{ template "airflow.name" . }}-rabbitmq
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "airflow.name" . }}-rabbitmq
  ports:
    - name: node
      protocol: TCP
      port: {{ .Values.ports.rabbitmqNode }}
      targetPort: node
    - name: management
      protocol: TCP
      port: {{ .Values.ports.rabbitmqManagement }}
      targetPort: management

